/*******************************
*	File generated by ast_generator.py, DO NOT MODIFY!
*******************************/

#ifndef EXPR_FWD_H
#define EXPR_FWD_H

struct Binary;
struct Grouping;
struct Unary;
struct Ast_literal;

#endif
