/*******************************
*	File generated by ast_generator.py, DO NOT MODIFY!
*******************************/

#ifndef EXPR_H
#define EXPR_H

#include <memory>

#include "../Token/token.h"
#include "../Variant/literal.h"
#include "../Visitor/mutable_state_visitor.h"

struct Binary;
struct Grouping;
struct Unary;
struct Ast_literal;

struct Expr {
	virtual void accept(Mutable_state_visitor&) = 0;
};

struct Binary: public Expr {
	std::shared_ptr<Expr> left;
	Token op;
	std::shared_ptr<Expr> right;
	Binary(std::shared_ptr<Expr>, Token, std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct Grouping: public Expr {
	std::shared_ptr<Expr> expr;
	Grouping(std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct Unary: public Expr {
	Token op;
	std::shared_ptr<Expr> right;
	Unary(Token, std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct Ast_literal: public Expr {
	Literal value;
	Ast_literal(Literal);
	void accept(Mutable_state_visitor&);
};


#endif
