/*******************************
*	File generated by ast_generator.py, DO NOT MODIFY!
*******************************/

#ifndef EXPR_HPP
#define EXPR_HPP

#include <memory>

#include "../Token/token.hpp"
#include "../Variant/literal.hpp"
#include "../Visitor/mutable_state_visitor.hpp"

struct Expr {
	virtual void accept(Mutable_state_visitor&) = 0;
};

struct Assign: public Expr {
	Token name;
	std::shared_ptr<Expr> value;
	Assign(Token, std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct Binary: public Expr {
	std::shared_ptr<Expr> left;
	Token op;
	std::shared_ptr<Expr> right;
	Binary(std::shared_ptr<Expr>, Token, std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct Grouping: public Expr {
	std::shared_ptr<Expr> expr;
	Grouping(std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct Unary: public Expr {
	Token op;
	std::shared_ptr<Expr> right;
	Unary(Token, std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct Ast_literal: public Expr {
	Literal value;
	Ast_literal(Literal);
	void accept(Mutable_state_visitor&);
};

struct Logical: public Expr {
	std::shared_ptr<Expr> left;
	Token op;
	std::shared_ptr<Expr> right;
	Logical(std::shared_ptr<Expr>, Token, std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct Variable: public Expr {
	Token name;
	Variable(Token);
	void accept(Mutable_state_visitor&);
};


#endif
