/*******************************
*	File generated by ast_generator.py, DO NOT MODIFY!
*******************************/

#ifndef EXPR_FWD_HPP
#define EXPR_FWD_HPP

struct Assign;
struct Binary;
struct Grouping;
struct Unary;
struct Ast_literal;
struct Logical;
struct Variable;

#endif
