/*******************************
*	File generated by ast_generator.py, DO NOT MODIFY!
*******************************/

#include <memory>
#include <vector>

#include "expr.h"
#include "../Visitor/mutable_state_visitor.h"

#include "stmt.h"

Block::Block(std::vector<std::shared_ptr<Stmt>> p_statements):
	statements {p_statements} {}

void Block::accept(Mutable_state_visitor& visitor) {
	visitor.visit(*this);
}

Expression::Expression(std::shared_ptr<Expr> p_expression):
	expression {p_expression} {}

void Expression::accept(Mutable_state_visitor& visitor) {
	visitor.visit(*this);
}

Print::Print(std::shared_ptr<Expr> p_expression):
	expression {p_expression} {}

void Print::accept(Mutable_state_visitor& visitor) {
	visitor.visit(*this);
}

Var::Var(Token p_name, std::shared_ptr<Expr> p_initializer):
	name {p_name}, initializer {p_initializer} {}

void Var::accept(Mutable_state_visitor& visitor) {
	visitor.visit(*this);
}

