/*******************************
*	File generated by ast_generator.py, DO NOT MODIFY!
*******************************/

#ifndef STMT_HPP
#define STMT_HPP

#include <memory>
#include <vector>

#include "expr.hpp"
#include "Visitor/mutable_state_visitor.hpp"

struct Stmt {
	virtual void accept(Mutable_state_visitor&) = 0;
	virtual ~Stmt() {};
};

struct Block: public Stmt {
	std::vector<std::shared_ptr<Stmt>> statements;
	Block(std::vector<std::shared_ptr<Stmt>>);
	void accept(Mutable_state_visitor&);
};

struct Expression: public Stmt {
	std::shared_ptr<Expr> expression;
	Expression(std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct If: public Stmt {
	std::shared_ptr<Expr> condition;
	std::shared_ptr<Stmt> then_branch;
	std::shared_ptr<Stmt> else_branch;
	If(std::shared_ptr<Expr>, std::shared_ptr<Stmt>, std::shared_ptr<Stmt>);
	void accept(Mutable_state_visitor&);
};

struct Print: public Stmt {
	std::shared_ptr<Expr> expression;
	Print(std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct Var: public Stmt {
	Token name;
	std::shared_ptr<Expr> initializer;
	Var(Token, std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&);
};

struct While: public Stmt {
	std::shared_ptr<Expr> condition;
	std::shared_ptr<Stmt> body;
	While(std::shared_ptr<Expr>, std::shared_ptr<Stmt>);
	void accept(Mutable_state_visitor&);
};


#endif
