/*******************************
*	File generated by ast_generator.py, DO NOT MODIFY!
*******************************/

#ifndef STMT_FWD_H
#define STMT_FWD_H

struct Expression;
struct Print;
struct Var;

#endif
