/*******************************
*	File generated by ast_generator.py, DO NOT MODIFY!
*******************************/

#ifndef STMT_HPP
#define STMT_HPP

#include <memory>
#include <vector>

#include "expr.hpp"
#include "Visitor/mutable_state_visitor.hpp"
#include "Token/token.hpp"

struct Stmt {
	virtual void accept(Mutable_state_visitor&) = 0;
	virtual ~Stmt() = default;
};

struct Block: public Stmt {
	std::vector<std::shared_ptr<Stmt>> statements;
	explicit Block(std::vector<std::shared_ptr<Stmt>>);
	void accept(Mutable_state_visitor&) override;
};

struct Expression: public Stmt {
	std::shared_ptr<Expr> expression;
	explicit Expression(std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&) override;
};

struct Function: public Stmt {
	Token name;
	std::vector<Token> params;
	std::vector<std::shared_ptr<Stmt>> body;
	explicit Function(Token, std::vector<Token>, std::vector<std::shared_ptr<Stmt>>);
	void accept(Mutable_state_visitor&) override;
};

struct Return: public Stmt {
	Token keyword;
	std::shared_ptr<Expr> value;
	explicit Return(Token, std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&) override;
};

struct If: public Stmt {
	std::shared_ptr<Expr> condition;
	std::shared_ptr<Stmt> then_branch;
	std::shared_ptr<Stmt> else_branch;
	explicit If(std::shared_ptr<Expr>, std::shared_ptr<Stmt>, std::shared_ptr<Stmt>);
	void accept(Mutable_state_visitor&) override;
};

struct Print: public Stmt {
	std::shared_ptr<Expr> expression;
	explicit Print(std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&) override;
};

struct Var: public Stmt {
	Token name;
	std::shared_ptr<Expr> initializer;
	explicit Var(Token, std::shared_ptr<Expr>);
	void accept(Mutable_state_visitor&) override;
};

struct While: public Stmt {
	std::shared_ptr<Expr> condition;
	std::shared_ptr<Stmt> body;
	explicit While(std::shared_ptr<Expr>, std::shared_ptr<Stmt>);
	void accept(Mutable_state_visitor&) override;
};


#endif
