/*******************************
*	File generated by ast_generator.py, DO NOT MODIFY!
*******************************/

#ifndef STMT_FWD_HPP
#define STMT_FWD_HPP

struct Block;
struct Expression;
struct If;
struct Print;
struct Var;
struct While;

#endif
